export global Icons {
    in property <image> arrow-left:  @image-url("../../icons/arrow-left.svg");
    in property <image> chevron-right:  @image-url("../../icons/chevron-right.svg");
    in property <image> lib-tab:  @image-url("../../icons/lib.svg");
    in property <image> track-tab:  @image-url("../../icons/track.svg");
    in property <image> insights-tab:  @image-url("../../icons/stats.svg");
    in property <image> settings-tab:  @image-url("../../icons/gear.svg");
}
