import { ScrollView } from "std-widgets.slint";
import { EventData, EventDataWithChildren } from "../../types.slint";
import { AppLogic } from "../../logic.slint";
import { Label } from "../../components/label.slint";

export component DetailsComponent inherits VerticalLayout {
    in-out property <bool> showing-details;
    in-out property <EventDataWithChildren> active-details;

    padding: 10px;
    spacing: 15px;

    HorizontalLayout {
        Label {
            horizontal-alignment: TextHorizontalAlignment.left;
            text: root.active-details.name;
            font-size: 20px;
            font-weight: 700;
        }

        // Back Button
        HorizontalLayout {
            alignment: end;
            TouchArea {
                clicked => {
                    root.showing-details = false;
                }
                HorizontalLayout {
                    spacing: 5px;
                    Image {
                        source: @image-url("../../../icons/arrow-left.svg");
                        width: 16px;
                        colorize: #4A90E2;
                    }

                    Label {
                        text: "Back to Main";
                        color: #4A90E2;
                        font-weight: 400;
                    }
                }
            }
        }
    }

    ScrollView {
        VerticalLayout {
            spacing: 8px;
            for sub-event in root.active-details.sub-events: Rectangle {
                height: 50px;
                background: white;
                border-radius: 8px;
                HorizontalLayout {
                    padding: 10px;
                    spacing: 10px;
                    Image {
                        source: sub-event.svg-icon;
                        width: 24px;
                        colorize: #4A90E2;
                    }

                    Label {
                        text: sub-event.name;
                        vertical-alignment: center;
                    }

                    Rectangle { } // Spacer
                        Label {
                        text: sub-event.event-occurrence;
                        vertical-alignment: center;
                        color: #666;
                    }
                }

                TouchArea {
                    clicked => {
                        AppLogic.event-clicked(sub-event.id);
                    }
                }
            }
        }
    }
}
