import { ScrollView, VerticalBox } from "std-widgets.slint";

import { EventData } from "types.slint";

import { TabItem } from "elements/tab_item.slint";
 
import { TrackPage } from "pages/track.slint";

  enum AppPage { Library, Track, Insights, Settings }

export component App inherits Window {
    min-width: 320px;
    min-height: 400px;
    preferred-width: 500px;
    preferred-height: 600px;
    title: "Event Tracker";
    background: #f4f4f9;
    in property <[EventData]> events;
    callback event-clicked(int);
    callback request-events();

    // Navigation State (Default to index 1: Track)
    private property <AppPage> active-tab: AppPage.Track;

    VerticalLayout {
        Rectangle {
            vertical-stretch: 1;
            if (active-tab == AppPage.Library): Text {
                text: "Library Page";
            }
            if (active-tab == AppPage.Track): TrackPage {
                events: root.events;
                event-clicked(id) => {
                    root.event-clicked(id)
                }
            }
            if (active-tab == AppPage.Insights): Text {
                text: "Insights Page";
            }
            if (active-tab == AppPage.Settings): Text {
                text: "Settings Page";
            }
        }

        Rectangle {
            height: 65px;
            background: white;
            border-color: #e0e0e0;
            border-width: 1px;

            HorizontalLayout {
                padding-top: 5px;
                padding-bottom: 5px;
                TabItem {
                    text: "Library";
                    icon: @image-url("../icons/lib.svg");
                    active: active-tab == AppPage.Library;
                    clicked => {
                        active-tab = AppPage.Library;
                    }
                }

                TabItem {
                    text: "Track";
                    icon: @image-url("../icons/track.svg");
                    active: active-tab == AppPage.Track;
                    clicked => {
                        active-tab = AppPage.Track;
                    }
                }

                TabItem {
                    text: "Insights";
                    icon: @image-url("../icons/stats.svg");
                    active: active-tab == AppPage.Insights;
                    clicked => {
                        active-tab = AppPage.Insights;
                    }
                }

                TabItem {
                    text: "Settings";
                    icon: @image-url("../icons/gear.svg");
                    active: active-tab == AppPage.Settings;
                    clicked => {
                        active-tab = AppPage.Settings;
                    }
                }
            }
        }
    }
}
