import { Palette } from "std-widgets.slint";
import { AppLogic } from "logic.slint";


export global Theme {
    out property <bool> is-dark <=> AppLogic.is-dark;
    in-out property <length> default-font-size: 20px;
    in-out property <string> default-font-family:  "Noto Sans";
    out property <length> padding: Math.max(4px, Math.round(default-font-size / 4px) * 1px);

    out property <color> default-font-color : self.is-dark ? #bcbfce : #01010e;
    out property <color> default-badge-color : #6a7cd1;
 

    public function set-dark(flag: bool) {
      AppLogic.is-dark = flag;
        Palette.color-scheme = is-dark ? ColorScheme.dark : ColorScheme.light;
    }

    public function toggle() {
       AppLogic.is-dark = !AppLogic.is-dark;
        Palette.color-scheme = is-dark ? ColorScheme.dark : ColorScheme.light;
    }
}